app/models/task.py
from app import db
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


class Task(db.Model):
    __tablename__ = 'tasks'

    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(120), nullable=False)
    content = db.Column(db.String(), nullable=False)
    user_id = db.Column(db.Integer(),  db.ForeignKey('users.id'),  nullable=False)
    pendent = db.Column(db.Boolean())

    def __init__(self, title, content, user_id):
        self.title = title
        self.content = content
        self.user_id = user_id
        self.pendent = 1
    
    def __repr__(self):
        return str({'id': self.id, 'title': self.title, 'content': self.content, 'pendente': self.pendent})

class TaskForm(FlaskForm):
    title = StringField('Título', validators=[DataRequired(), Length(min=10)])
    content = TextAreaField('Conteúdo', validators=[DataRequired(), Length(min=10)])
    submit = SubmitField()

app/controllers/entry.py
from app import bcrypt, db, login_manager, serializer, mail
from app.models.user import User, UserSignupForm, UserLoginForm
from CONFIG import SALT_SERIALIZER, EMAIL_USERNAME
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from flask_mail import Message
from itsdangerous import BadSignature, SignatureExpired


entry_route = Blueprint('entry', __name__)


@login_manager.user_loader
def get_user(id_user):
    return User.query.filter_by(id=id_user).first()

@entry_route.route('/')
@entry_route.route('/login', methods=['GET', 'POST'])
def login():
    form = UserLoginForm()
    if request.method == 'POST':
        form = form.data
        if User.query.filter_by(email=form['email']).first():
            user = User.query.filter_by(email=form['email']).first()
            if user.verifyPass(form['pwd']):
                login_user(user)
                return redirect(url_for('tasks.home'))
            else:
                flash("Senha incorreta!")
                return redirect(url_for('entry.login'))
        else:
            flash('Não existe usuário cadastrado com esse Email!')
            return redirect(url_for('entry.login'))
    if current_user.is_authenticated:
        return redirect(url_for('tasks.home'))
    return render_template('entry/login.html', form=form)


@entry_route.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("entry.login"))


@entry_route.route('/signup', methods=['GET', 'POST'])
def signup():
    form = UserSignupForm()
    if request.method == 'POST':
        
        if User.query.filter_by(email=form.email.data).first():
            flash('Esse nome de usuário já está cadastrado!')
            return redirect(url_for('entry.signup'))
        else:
            
            new_user = User(form.name.data, form.email.data, bcrypt.generate_password_hash(form.pwd.data)) 

            db.session.add(new_user)
            db.session.commit()

            token = serializer.dumps({'id':new_user.id, "email": new_user.email}, salt=SALT_SERIALIZER)

            url_confirm = url_for("entry.email_confirmation", token=token, _external=True)
            subject = f'Mensagem para confirmação do seu email {new_user.name}'
            body = f"""Acesse o link abaixo para confirmar seu endereço de email ou copie e cole no seu navegador
                {url_confirm}
                Obrigado por utilizar nossos serviços"""
            message = Message(subject=subject, sender=EMAIL_USERNAME, recipients=[new_user.email], body=body)
            mail.send(message)

            return redirect(url_for('entry.login'))
    return render_template("entry/signup.html", form=form)


@entry_route.route('/gerando-chave')
@login_required
def generate_token():
    token = serializer.dumps({'id':current_user.id, "email":current_user.email}, salt=SALT_SERIALIZER)

    url_confirm = url_for("entry.email_confirmation", token=token, _external=True)
    subject = f'Mensagem para confirmação do seu email {current_user.name}'
    body = f"""Acesse o link abaixo para confirmar seu endereço de email ou copie e cole no seu navegador
        {url_confirm}
        Obrigado por utilizar nossos serviços"""
    message = Message(subject=subject, sender=EMAIL_USERNAME, recipients=[current_user.email], body=body)
    mail.send(message)


    return redirect(url_for('entry.login'))

@entry_route.route('/confirmação-de-email/<token>')
def email_confirmation(token):
    try:
        user_info = serializer.loads(token, salt=SALT_SERIALIZER)

    except SignatureExpired:
        return render_template('entry/error-confirm.html', error=1)
    
    except  BadSignature:
        return render_template('entry/error-confirm.html', error=2)
    
    user = User.query.filter_by(email=user_info['email']).first()
    if user.email_confirmed:
        flash(f"Olá {user.name}, seu email já foi confirmado anteriormente!")
        return redirect(url_for('entry.login'))
    user.email_confirmed = True
    db.session.commit()
    flash(f"Olá {user.name}, seu email foi confirmado com sucesso!")
    return redirect(url_for('entry.login'))


@entry_route.route('/esqueci-a-senha', methods=['GET', 'POST'])
def request_password():
    if request.method == 'POST':
        if User.query.filter_by(email=request.form['email']).first():
            email = request.form['email']

            token = serializer.dumps(email, salt='email-token-confirmation')
            urlConfirm = url_for('entry.new_pwd', token=token, _method='GET', _external=True)

            body =  f"""Segue abaixo o link para recurepação de senha!
                        {urlConfirm}"""
            message = Message(subject='Mensagem com link para redefinição de senha',
                            recipients=[email],
                            body=body,  sender=EMAIL_USERNAME)
            
            mail.send(message)

            email = email.split('@')
            print(email)
            email = email[0][0:4] + "*"*(len(email[0])-4) + "@" +email[1]
            print(email)

            message = f'Email com link para redefinição de senha foi enviado para {email}'
        else:
            message = f"email '{request.form['email']} não é um email registrado!'"
        flash(message)
        return redirect(url_for('entry.request_password'))
    return render_template('entry/request-pwd.html')

@entry_route.route('/nova-senha/<token>', methods=['GET'])
@entry_route.route('/nova-senha', methods=['POST'])
def new_pwd(token=0):
    if request.method == 'GET':
        try:
            email = serializer.loads(token, salt='email-token-confirmation')
        except SignatureExpired:
            return "<h1>Token expirou!</h1>"
        except BadSignature:
            return "<h1>Token corrompido!</h1>"
        
        user = User.query.filter_by(email=email).first()
        return render_template('entry/new-pwd.html', user={'id':user.id, 'email':user.email})
    
    new_password = request.form['pwd']
    user = User.query.filter_by(email=request.form['email']).first()
    user.pwd = bcrypt.generate_password_hash(new_password)
    db.session.commit()
    if current_user:
        logout_user()
    return redirect(url_for('entry.login'))
 

app/controllers/tasks.py
from app import db
from app.models.task import TaskForm, Task
from app.controllers.decorators import email_confirmation_required
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify, json
from flask_login import login_required, current_user

task_route = Blueprint("tasks", __name__)


"""     ROTAS A SEREM ADICIONADAS 

OK        * /tasks/ (get) - faz o carregamento de todas as tarefas existestes, haverá filtro entre
                          as tarefas pendentes e já concluídas;
OK        * /tasks/create (GET) - carrega o formulário para criação de tarefas;
OK        * /tasks/create (POST) - faz  o envio das informações inseridas;
OK        * /tasks/id (get) - carregamento de uma tarefa;
OK        * /tasks/id/completed (PUT) - alterar o status de pendent True(1) para False (0);
OK        * /tasks/id/update (get) - carregamento de formulário para alterações;
OK        * /tasks/id/update (PUT) - envio de alterações realizadas;
OK        * /tasks/id/delete (DELETE) - realizar exclusão de tarefa;;

"""


@task_route.route('/home/')
@login_required
def home():
    page_pendent = request.args.get('pendent_page', default=1, type=int)
    page_completed = request.args.get('completed_page', default=1, type=int)
    per_page = 9

    tasks_pendent = Task.query.filter_by(user_id=current_user.id, pendent=True).paginate(page=page_pendent, per_page=per_page)
    tasks_completed = Task.query.filter_by(user_id=current_user.id, pendent=False).paginate(page=page_completed, per_page=per_page)

    return render_template('tasks/read.html', tasks_pendent=tasks_pendent, tasks_completed=tasks_completed)


@task_route.route('/<id>', methods=['PUT'])
@login_required
def completed(id):
    if Task.query.filter_by(id=id).first():
        task = Task.query.filter_by(id=id).first()
        if task.pendent == 1:
            task.pendent = 0
            db.session.commit()
            flash(f'Tarefa foi concluida com sucesso!')
            return jsonify(status='completed')
        else:
            flash(f'Tarefa já está concluida!')
            return jsonify(status='already-completed')

    else:
        return jsonify(status='not-completed')


@task_route.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = TaskForm()
    if form.is_submitted():
        new_task = Task(form.title.data, form.content.data, user_id=current_user.id)
        print(new_task)
        db.session.add(new_task)
        db.session.commit()
        return redirect(url_for('tasks.home'))
    return render_template('tasks/create.html', form=form)


@task_route.route('/<id>')
@login_required
def read_task(id):
    if Task.query.filter_by(id=id).first():
        task = Task.query.filter_by(id=id).first()
        return render_template('tasks/read-task.html', task=task)
    else:
        flash("Nenhum tarefa encontrada!")
        return redirect(url_for('tasks.home'))
    

@task_route.route('/<id>/update', methods=['GET'])
@login_required
def update_form(id):
    if Task.query.filter_by(id=id).first():
        task = Task.query.filter_by(id=id).first()
        return render_template('tasks/update-task.html', task=task)
    else:
        flash(f"Tarefa de id '{id}' não encontrada!")
        return redirect(url_for('tasks.home'))



@task_route.route('/<id>/update', methods=['PUT'])
@login_required
def update_put(id):
    task_update = request.json
    task = Task.query.filter_by(id=id).first()
    task.title = task_update['title']
    task.content = task_update['content']
    db.session.commit()
    
    return jsonify(status='ok', url=url_for('tasks.read_task', id=id))


@task_route.route('/<id>/delete', methods=['DELETE'])
@login_required
def delete(id):
    task_to_delete = Task.query.filter_by(id=id).first()
    try:
        db.session.delete(task_to_delete)
        db.session.commit()
    except Exception as erro:
        return jsonify(erros=erro)
    else:
        return jsonify(status='ok', url=url_for('tasks.home'))

app/templates/tasks/base.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} {% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/tasks/mobile.css')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/tasks/media-queries.css')}}">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
  <style>
    #powered {
      color: purple;
      font-weight: bold;
      transition: font-size .5s, text-decoration .5s;
    }
    #powered:hover {
      text-decoration: underline;
      font-size: 18px;
      color: purple;
    }
  </style>
  {% block head %} {% endblock %}

</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('tasks.home')}}">Tasks</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('tasks.home')}}">Home | listar tarefas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('tasks.create')}}">Criar tarefa</a>
          </li>
          <li class="nav-item">
            <a id="powered" class="nav-link" href="https://github.com/felipe-fjs" target="_blank">Feito Por Felipe Joaquim</a>
          </li>
          
          {% if not current_user.email_confirmed %}
            <li class="nav-item" id="confirm-email">
              <span class="nav-link">Seu email ainda não foi confirmado! Clique <a href="{{ url_for('entry.generate_token')}}">aqui</a> para gerar uma nova chave de validação se tiver tido algum problema</span>
            </li>
          {% endif %}
        </ul>
        <span class="d-flex">
          <span class="me-2">{{ current_user.name }}</span>
          <a class="nav-link" href="{{ url_for('entry.logout') }}">Sair</a>
        </span>
      </div>
    </div>
  </nav>

  {% block content %} {% endblock %}
  <script src="../../static/js/bootstrap.bundle.min.js"></script>
</body>

</html>

app/templates/tasks/create.html
{% extends "tasks/base.html" %}

      {% block title %}Criar tarefa {% endblock %}>


{% block content %}
    <main>
        <section class="form-task">
            <form action="{{ url_for('tasks.create')}}" method="post">
                <div>
                   {{ form.title.label }}
                   {{ form.title(class='form-control', placeholder='título da tarefa aqui..')}}
                </div>
                <div>
                    {{ form.content.label }}
                    {{ form.content(class='form-control', placeholder='Tarefa aqui...')}}
                </div>
                <div>
                  
                  <button type="submit" class="btn btn-success">Criar Tarefa</button>
                  <button type="reset" class="btn btn-warning">Limpar</button>
                </div>
            </form>
        </section>
    </main>

{% endblock %}

app/templates/tasks/read-task.html
{% extends "tasks/base.html" %}

{% block title %} {{ task.title[0:20]}} {% endblock %}

{% block head %} {% endblock %}

{% block content %}
<main>
  <section class="form-task">
    {% set messages = get_flashed_messages() %}
    {% if messages %}
    <div>
      {% for message in messages %}
      {{message}}
      {% endfor %}
    </div>
    {% endif%}
    <form>
      <div>

        <label for="title">Título</label>

        <input type="text" name="title" id="title" class="form-control" value="{{ task.title }}" disabled>

      </div>
      <div>
        <label for="content">Conteúdo</label>

        <textarea type="text" name="content" id="content" class="form-control" disabled>{{ task.content }}</textarea>

      </div>
      <div>

        <button type="button" class="btn btn-success"
          onclick="taskCompleted(`{{url_for('tasks.completed', id=task.id)}}`)" id="btn-conclude">Concluir</button>

        <button type="button" id="a-update" class="btn btn-primary" onclick='openUpdate()'>Editar tarefa</button>

        <button type="button" id="btn-delete" class="btn btn-danger">Excluir</button>

        <div class="delete-check-hiden" id="delete-check" class="alert alert-warning">
          Tem certeza que deseja excluir essa tarefa?
          <button type="button" class="btn btn-danger" id="delete-confirm">Excluir</button>
          <button type="button" id="delete-cancel" class="btn btn-warning" >Cancelar</button>
        </div>

      </div>
    </form>
  </section>
</main>


<script>
  function deleteCheckHiden() {
    let btn_conclude = document.getElementById('btn-conclude')
    let a_update = document.getElementById('a-update')
    let btn_delete = document.getElementById('btn-delete')
    let div_check = document.getElementById('delete-check') 
    if (document.getElementById('delete-check').style.display !== 'block') {

      btn_conclude.style.display = 'none'
      a_update.style.display = 'none'
      btn_delete.style.display = 'none'
      div_check.style.display = 'none'
      div_check.style.display = 'block'

    } else {

      btn_conclude.style.display = 'initial'
      a_update.style.display = 'initial'
      btn_delete.style.display = 'initial'
      div_check.style.display = 'initial'
      div_check.style.display = 'none'

    }
  }
  

  function taskCompleted(url) {
    fetch(url, { method: 'PUT' }).then(response => response).then(data => { window.location.reload() })
  }

  function openUpdate (){
    const url = "{{ url_for('tasks.update_form', id=task.id)}}"
    window.open(url, "_self")
  }

  document.getElementById('btn-delete').addEventListener('click', deleteCheckHiden)
  document.getElementById('delete-cancel').addEventListener('click', deleteCheckHiden)
  document.getElementById('delete-confirm').addEventListener('click', () => {
    fetch("{{ url_for('tasks.delete', id=task.id)}}", {
      method: "DELETE"
    })
    .then(response => response.json())
    .then(data => {
      console.log(data)
      window.open(data['url'], '_self')
    })
  })
</script>
{% endblock %}

app/templates/tasks/read.html
{% extends "tasks/base.html" %}
{% block title %}Tarefas{% endblock %}

{% block head %}
    <style>
        .completed, .completed_page {
            display: none;
        }
    </style>
{% endblock %}

{% block content %}
<main class="container">
    <div class="row justify-content-center">
        <div class="bg-tasks" onclick>
            <span id="main-head">
                <h1 style="display: inline;">Tarefas</h1>
                <span id="span-filtros">
                    <button class="btn btn-warning" type="button" onclick="tasksPendents()">Pendentes</button>
                    <button class="btn btn-success" type="button" onclick="tasksCompleteds()">Concluídas</button>
                </span>
            </span>
            <!-- BLOCO QUE CARREGARÁ AS TAREFAS PENDENTES -->
            {% if tasks_pendent %}
                {% for task in tasks_pendent %}
                    <div class="task pendent"
                        onclick="window.location.href = `{{url_for('tasks.read_task', id=task.id)}}`"
                        title="abrir tarefa">

                        <a href="{{ url_for('tasks.read_task', id=task.id)}}">{{ task.title }} </a>
                        
                        <button  onclick="completed('{{task.id}}', `{{url_for('tasks.completed', id=task.id)}}`)" title="completar tarefa">
                            <span class="material-symbols-outlined">check</span>
                        </button>
                        
                    </div>
                {% endfor %}

            {% else %}
                <h2 class="alert alert-warning">Não há tarefas cadastradas, crie novas em 
                    <a href="{{ url_for('tasks.create')}}">Criar tarefas</a>
                </h2>
            {% endif %}

            <!-- BLOCO QUE CARREGARÁ AS TAREFAS CONCLUÍDAS -->
            {% if tasks_completed %}
                {% for task in tasks_completed %}
                    <div class="task completed"
                        onclick="window.location.href = `{{url_for('tasks.read_task', id=task.id)}}`"
                        title="abrir tarefa">

                        <a href="{{ url_for('tasks.read_task', id=task.id)}}">{{ task.title }} </a>
                    </div>
                {% endfor %}

            {% else %}
                <h2 class="alert alert-warning">Ainda não há tarefas concluídas!</h2>
            {% endif %}

            <span id="new_task" class="material-symbols-outlined btn btn-primary" 
                title="Adicionar nova tarefa"
                onclick='location.href = `{{url_for("tasks.create")}}`'>
                    add_circle
            </span>

            <!-- Div para exibição das páginas existentes de tarefas do usuário -->
            <div id="pages" title="shift + rolagem para ir à esquerda ou direita"> 
                <!-- Carrega as páginas disponíveis para as tarefas pendentes -->
                {% if tasks_pendent.pages >= 1 %}
                    {% for page in range(1, tasks_pendent.pages + 1) %}
                        <a class="page pendent_page" href="{{ url_for('tasks.home', pendent_page=page)}}">{{ page }}</a>
                    {% endfor %}
                {% endif %}

                <!-- Carrega as páginas disponíveis para as tarefas concluídas -->
                {% if tasks_completed.pages >= 1 %}
                    {% for page in range(1, tasks_completed.pages + 1) %}
                        <a class="page completed_page" href="{{ url_for('tasks.home', completed_page=page)}}">{{ page }}</a>
                    {% endfor %}
                {% else %}
                    
                {% endif %}
            </div>
        </div>
    </div>
</main>

<script>
    function completed(url, task_id) {
        fetch(url, {
            method: "PUT"
        })
            .then(response => response.json())
            .then(data => {
                console.log(data)
                window.location.href = "{{ url_for('tasks.home')}}"

            })
    } 
    const task_completed = document.querySelectorAll('.completed')
    const task_pendent = document.querySelectorAll('.pendent')
    const page_pendent = document.querySelectorAll('.pendent_page')
    const page_completed = document.querySelectorAll('.completed_page')
    function tasksCompleteds (){
        task_completed.forEach(task => {
            task.style.display = 'block'
        })
        task_pendent.forEach(task => {
            task.style.display = 'none'
        })
        page_completed.forEach(page => {
            page.style.display = 'initial'
        })
        page_pendent.forEach(page => {
            page.style.display = 'none'
        })

    }
    function tasksPendents (){
        task_completed.forEach(task => {
            task.style.display = 'none'
        })
        task_pendent.forEach(task => {
            task.style.display = 'block'
        })
        page_completed.forEach(page => {
            page.style.display = 'none'
        })
        page_pendent.forEach(page => {
            page.style.display = 'initial'
        })
    }
    window.onload = () => {
        const url = new URLSearchParams(window.location.search);

        if (url.has("completed_page")) {
            tasksCompleteds();
        } else {
            tasksPendents();
        }
    }
</script>
{% endblock %}

app/templates/tasks/update-task.html
{% extends "tasks/base.html" %}

  {% block title %}{{ task.title[0:10]}} {% endblock %}

  {% block head %} {% endblock %}

  {% block content %}

    <main>
        <section class="form-task">
            <form id="update-form">
                <div>
                  <label for="title">Título</label>
                  <input type="text" name="title" id="title" class="form-control" value="{{ task.title }}">
                </div>
                <div>
                  <label for="content">Conteúdo</label>
                  <textarea type="text" name="content" id="content" class="form-control">{{ task.content }}</textarea>
                </div>
                <div>
                  <button type="submit" class="btn btn-success" >Salvar</button>
                  <button type="reset" class="btn btn-danger" onclick="window.location.href = `{{ url_for('tasks.read_task', id=task.id) }}`">Cancelar</button>
                </div>
            </form>
        </section>
    </main>


    <script>
      document.getElementById('update-form').addEventListener('submit', function (event) {
        event.preventDefault()

        let task = {'title': document.getElementById('title').value, 'content': document.getElementById('content').value}

        fetch("{{ url_for('tasks.update_put', id=task.id)}}", {
          method : 'PUT',
          body: JSON.stringify(task),
          headers: {
            "Content-type": "application/json; charset=UTF-8"
          },
        })
        .then(response => response.json())
        .then(data => {
          console.log(data)
          window.location.href = "{{ url_for('tasks.read_task', id=task.id)}}"
        })
      } )
    </script>
  {% endblock %}